kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: traefik
  external-dns.alpha.kubernetes.io/hostname: 'traefik.heemels.net'
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
  type: LoadBalancer